itproger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('news/', include('news.urls', namespace='news')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('info/', views.info, name='info'),
]

news/urls.py
from django.urls import path
from news import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsHomeView.as_view(), name='home'),
    path('create/', views.NewsCreateView.as_view(), name='create'),
    path('<int:pk>/', views.NewsDetailView.as_view(), name='news-detail'),
    path('<int:pk>/update/', views.NewsUpdateView.as_view(), name='news-update'),
    path('<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news-delete')
]

main/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField('Название', max_length=50, default='Empty name')
    anons = models.CharField('Анонс', max_length=250)
    full_text = models.TextField('Статья')
    date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.title

    @property
    def absolute_url(self):
        return f'/news/{self.id}'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ('-date',)

news/forms.py
from .models import Article
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'anons', 'full_text', 'date']
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название статьи'
            }),
            'anons': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Анонс статьи'
            }),
            'full_text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст статьи'
            }),
            'date': DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дата публикации'
            })
        }

main/views.py
from django.shortcuts import render


def index(request):
    data = {
        'title': 'Главная страница?',
        'values': ['text1', 'text2', 'text3'],
        'obj': {
            'a': 'qwe',
            'b': 'asd',
            'c': 'zxc'
        }
    }
    return render(request, 'main/index.html', data)


def about(request):
    return render(request, 'main/about.html')


def info(request):
    return render(request, 'main/info.html')

news/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Article
from .forms import ArticleForm
from django.views.generic import DetailView, UpdateView, DeleteView, ListView, CreateView


class NewsHomeView(ListView):
    model = Article


class NewsCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('news:home')


class NewsDetailView(DetailView):
    model = Article
    context_object_name = 'article'
    # template_name = 'news/article_detail.html'


class NewsUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('news:home')
    # template_name = 'news/article_form.html'


class NewsDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('news:home')
    # template_name = 'news/article_confirm_delete.html'

# def news_home(request):
#     news = Article.objects.order_by('-date')
#     return render(request, 'news/article_list.html', {'news': news})


# def create(request):
#     error = ''
#     if request.method == 'POST':
#         form = ArticleForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('news:home')
#         else:
#             error = 'Неверная форма'
#
#     form = ArticleForm()
#     data = {
#         'form': form,
#         'error': error
#     }
#
#     return render(request, 'news/article_form.html', data)

main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title %}Страница about{% endblock %}

{% block content %}
    <div class="features">
        <h1>Страница about</h1>
        <p>vjslfbvalkbfvlajbfvjabdlfkvba;fjv;ajkfv;kajbfvk;jabdfkjvbakjfbv;
            ahviurhgauehrg;aue;ga;kjfbvkajbvjbvkajfbvk
            jafbv;abfvbafkjvba;kfjbvkabfvkabfvbakfhgaehrharughaouhg;afbvkja
            bfvkjbdf;jvba;kfjbvjakbfvajdfbvauheroguheo
            ighroahiegoajbdfvkjabdfvjkadbfv;adfibhaoehrgoa;ehrafdbn</p>
        <button class="btn btn-danger">Бессмысленная кнопка</button>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>vjslfbvalkbfvlajbfvjabdlfkvba;fjv;ajkfv;kajbfvk;jabdfkjvbakjfbv;
            ahviurhgauehrg;aue;ga;kjfbvkajbvjbvkajfbvk
            jafbv;abfvbafkjvba;kfjbvkabfvkabfvbakfhgaehrharughaouhg;afbvkja
            bfvkjbdf;jvba;kfjbvjakbfvajdfbvauheroguheo
            ighroahiegoajbdfvkjabdfvjkadbfv;adfibhaoehrgoa;ehrafdbn</p>
        <button class="btn btn-warning">На страницу about</button>
        {% for el in values %}
            {% if el == 'text1' %}
                {% filter upper %}
                    <p>{{ el }}</p>
                {% endfilter %}
            {% endif %}
        {% endfor %}
        {{ obj.a }}
        {{ obj.c|upper }}
    </div>
{% endblock %}

main/templates/main/info.html
{% extends 'main/layout.html' %}

{% block title %}Страница info{% endblock %}

{% block content %}
    <div class="features">
        <h1>Страница info</h1>
        <p>vjslfbvalkbfvlajbfvjabdlfkvba;fjv;ajkfv;kajbfvk;jabdfkjvbakjfbv;
            ahviurhgauehrg;aue;ga;kjfbvkajbvjbvkajfbvk
            jafbv;abfvbafkjvba;kfjbvkabfvkabfvbakfhgaehrharughaouhg;afbvkja
            bfvkjbdf;jvba;kfjbvjakbfvajdfbvauheroguheo
            ighroahiegoajbdfvkjabdfvjkadbfv;adfibhaoehrgoa;ehrafdbn</p>
        <button class="btn btn-danger">Бессмысленная кнопка</button>
    </div>
{% endblock %}

main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/image_1.jpeg' %}" alt="Дополнительное описание">
        <span class="logo">itProger</span>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'main:home' %}"><li><i class="bi bi-house"></i>Главная</li></a>
            <a href="{% url 'main:about' %}"><li><i class="bi bi-person"></i>About</li></a>
            <a href="{% url 'main:info' %}"><li><i class="bi bi-journal"></i>Info</li></a>
            <a href="{% url 'news:home' %}"><li><i class="bi bi-megaphone"></i>News</li></a>
            <a href="{% url 'news:create' %}"><li><button class="btn btn-info"><i class="bi bi-plus-circle"></i>Add news</button></li></a>
        </ul>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

main/templates/main/test.html
<p>Проверка работы</p>

news/templates/news/article_confirm_delete.html
{% extends 'main/layout.html' %}

{% block title %}Удаление статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Удаление статьи</h1>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-success" type="submit">Удалить статью</button>
        </form>
    </div>
{% endblock %}

news/templates/news/article_detail.html
{% extends 'main/layout.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ article.title }}</h1>
        <p>{{ article.date }}</p>
        <p>{{ article.full_text }}</p>
        <a href="{% url 'news:news-delete' article.id %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'news:news-update' article.id %}" class="btn btn-info">Обновить</a>
    </div>
{% endblock %}

news/templates/news/article_form.html
{% extends 'main/layout.html' %}

{% block title %}Форма для добавления статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Форма для добавления статьи</h1>
        <form method="post">
            {% csrf_token %}

            {{ form.title }}<br>
            {{ form.anons }}<br>
            {{ form.full_text }}<br>
            {{ form.date }}<br>
            <span>{{ error }}</span>

            <button class="btn btn-success" type="submit">Добавить статью</button>
        </form>
    </div>
{% endblock %}

news/templates/news/article_list.html
{% extends 'main/layout.html' %}

{% block title %}Новости на сайте{% endblock %}

{% block content %}
    <div class="features">
        <h1>Новости на сайте</h1>
        {% if object_list %}
	        {% for el in object_list %}
		        <div class="alert alert-warning">
			        <h3>{{ el.title }}</h3>
			        <p>{{ el.anons }}</p>
					<a href="{% url 'news:news-detail' el.id %}" class="btn btn-warning">Читать детальнее</a>
		        </div>
	        {% endfor %}
        {% else %}
	        <p>У вас нет записей!</p>
        {% endif %}
    </div>
{% endblock %}

news/templates/news/create.html
{% extends 'main/layout.html' %}

{% block title %}Форма для добавления статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Форма для добавления статьи</h1>
        <form method="post">
            {% csrf_token %}

            {{ form.title }}<br>
            {{ form.anons }}<br>
            {{ form.full_text }}<br>
            {{ form.date }}<br>
            <span>{{ error }}</span>

            <button class="btn btn-success" type="submit">Добавить статью</button>
        </form>
    </div>
{% endblock %}

news/templates/news/details_view.html
{% extends 'main/layout.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ article.title }}</h1>
        <p>{{ article.date }}</p>
        <p>{{ article.full_text }}</p>
        <a href="{% url 'news-delete' article.id %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'news-update' article.id %}" class="btn btn-info">Обновить</a>
    </div>
{% endblock %}

news/templates/news/news-delete.html
{% extends 'main/layout.html' %}

{% block title %}Удаление статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Удаление статьи</h1>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-success" type="submit">Удалить статью</button>
        </form>
    </div>
{% endblock %}

news/templates/news/news_home.html
{% extends 'main/layout.html' %}

{% block title %}Новости на сайте{% endblock %}

{% block content %}
    <div class="features">
        <h1>Новости на сайте</h1>
        {% if news %}
	        {% for el in news %}
		        <div class="alert alert-warning">
			        <h3>{{ el.title }}</h3>
			        <p>{{ el.anons }}</p>
					<a href="{% url 'news-detail' el.id %}" class="btn btn-warning">Читать детальнее</a>
		        </div>
	        {% endfor %}
        {% else %}
	        <p>У вас нет записей!</p>
        {% endif %}
    </div>
{% endblock %}